# Server configuration
[server]
host = "127.0.0.1"
port = 3000
max_logging_level = "DEBUG"
pool_size = 10
recv_buffer_size = 8192  # Adjust the receive buffer size as needed
send_buffer_size = 8192  # Adjust the send buffer size as needed

validate_requests = true

[runtime]
worker_threads = 2

# Default retry configuration for all targets (if not overridden per target)
[retries]
strategy = "FixedInterval"
max_attempts = 2
base_delay_seconds = 2

# Default circuit breaker configuration for all targets (if not overridden per target)
[default_circuit_breaker_config]
max_failures = 3
reset_timeout_seconds = 30
half_open_attempts = 2

# List of target configurations
[[targets]]
path = "/api/service1"
url = "http://localhost:5001"
# Optional retry configuration for this specific target
retries = { strategy = "FixedInterval", max_attempts = 3, base_delay_seconds = 1 }
routing_header = "X-Api-Version"
routing_values = { "v1" = "http://localhost:5001/v1", "v2" = "http://localhost:5001/v2" }

# Optional circuit breaker configuration for this specific target
circuit_breaker_config = { max_failures = 2, reset_timeout_seconds = 5, half_open_attempts = 1 }

# Optional request transformations for this target
request_transforms = [
    { type = "Header", name = "X-Proxy-Inject", value = "Service1", operation = "Set" }
]

# Optional response transformations for this target
response_transforms = [
    { type = "Header", name = "X-Proxy-Modified", value = "true", operation = "Set" }
]

[[targets]]
path = "/api/service2"
url = "https://localhost:7277"
timeout_seconds = 3
cache_config = { ttl_seconds = 60, max_size = 50, serialize= true }
logging_config = { log_requests = true, log_responses = true }
authentication = {jwt_secret = "your_secret_key",type = "JWT" }


[[targets]]
path = "/api/service3"
url = "http://localhost:9003"
# Specific retry configuration for this target
retries = { strategy = "FixedInterval", max_attempts = 4, base_delay_seconds = 1 }
# Specific circuit breaker configuration for this target
circuit_breaker_config = { max_failures = 1, reset_timeout_seconds = 10, half_open_attempts = 1 }


[security_headers_config]
strict_transport_security = "max-age=31536000; includeSubDomains"
x_content_type_options = "nosniff"
x_frame_options = "DENY"
content_security_policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self';"
x_xss_protection = "1; mode=block"
referrer_policy = "no-referrer"
permissions_policy = "geolocation=(), microphone=(), camera=()"

[bot_detector]
allow = ["MyAndroidClient/1.0", "Pingdom.com_bot_version_1.1"]
deny = ["a", "b"]
patterns = [
    "(Pingdom.com_bot_version_).*",
    "(facebookexternalhit)/.*"
]
empty_user_agent_is_bot = true